# Generated by Django 4.2.1 on 2023-07-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('passw', models.CharField(max_length=300)),
                ('ques', models.CharField(default="What's your favorite food?", editable=False, max_length=200)),
                ('ans', models.CharField(max_length=30)),
            ],
        ),
    ]
